GRANT SELECT ON toad.tcx_config TO "PUBLIC";
GRANT UPDATE ON toad.tcx_config TO "PUBLIC";
GRANT SELECT ON toad.tcx_object_history TO "PUBLIC";
GRANT INSERT ON toad.tcx_object_history TO "PUBLIC";
GRANT UPDATE ON toad.tcx_object_history TO "PUBLIC";
GRANT DELETE ON toad.tcx_object_history TO "PUBLIC";
GRANT SELECT ON toad.tcx_objects TO "PUBLIC";
GRANT INSERT ON toad.tcx_objects TO "PUBLIC";
GRANT UPDATE ON toad.tcx_objects TO "PUBLIC";
GRANT DELETE ON toad.tcx_objects TO "PUBLIC";
GRANT SELECT ON toad.tcx_team_projects TO "PUBLIC";
GRANT INHERIT PRIVILEGES ON toad.toad TO "PUBLIC";